import axios from 'axios';
import Head from 'next/head';
import styled from 'styled-components';
import Banner from '../components/Banner';
import Movies from '../components/Movies';
import Header from '../components/Header';
import { useState } from 'react';

export default function Home({movies}) {
  const [search, setSearch] = useState("");
  console.log(movies)
  return (
      <>
        <Container>
          <Head>
            <title>Star Movies/Home</title>
            <meta name="description" content="Generated by create next app" />
          </Head>
          <Header
          search={search} 
          setSearch={setSearch}
          />
            <>
              <Banner/>
              <h1 className='title'>Movie Lists :</h1>
              <Cart>
                {movies.filter((item) => item.title.toLowerCase().includes(search))
                .map((movie, i) => (
                  <Movies movie={movie} key={i}/>
                ))}
              </Cart>
            </>
        </Container>
      </>
  )
}

const Container = styled.div`
  .title{
        font-size: 1rem;
        margin: 2rem 6rem;
        @media(max-width : 900px){
          margin: 2rem 1.5rem;
        } 
    }
`
const Cart = styled.div`
  width: 85%;
  margin: 0 auto;
  display: grid;
  gap: 1rem;
  grid-template-columns: repeat(auto-fit , minmax(180px, 1fr));
  margin-bottom: 2rem;
  @media(max-width : 900px){
    width: 90%;
  } 
`
export const getStaticProps = async () => {
  const res = await fetch(`https://api.themoviedb.org/3/trending/movie/week?api_key=74206488d4fb5a679b81bb45afcb8173`);
  const data = await res.json();
  const movies = data.results
  return{
    props : {
      movies
    }
  }
}
